#ifndef SECRETS_H
#define SECRETS_H

// ESP32 Wi-Fi and Dashboard Configuration Template
// ==================================================
// 
// IMPORTANT: This file is a TEMPLATE. Do not edit this file for your actual setup.
//
// Setup Instructions:
// 1. Copy this file to: ESP32/esp32_water_monitor_sender/secrets.h
// 2. Edit the copied file (secrets.h) with your actual values
// 3. NEVER commit secrets.h to version control
//
// The secrets.h file in the sketch directory is what the ESP32 code uses.
// Keep your Wi-Fi credentials and API keys out of version control!

#define WIFI_SSID "your-wifi-name"
#define WIFI_PASSWORD "your-wifi-password"
#define DEVICE_ID "ESP32-WATER-01"
#define API_KEY "replace_with_your_dashboard_api_key"
#define SERVER_URL "http://your-computer-lan-ip:3000/api/ingest"
#define CALIBRATION_COMMAND_URL "http://your-computer-lan-ip:3000/api/calibration/command"

#endif // SECRETS_H
